spring:
  datasource:
    url: jdbc:mysql://192.168.195.214:3306/hdu?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 321456987

  redis:
    host: 192.168.195.214
    database: 10
    port: 6379
    jedis:
      pool:
        max-active: 50
        max-idle: 20
        min-idle: 5

server:
  port: 81

logging:
  config: classpath:logback-spring.xml
  level:
    root: debug