spring:
  datasource:
    url: jdbc:mysql://localhost:3307/hdu?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

  redis:
    host: localhost
    database: 10
    port: 6379
    jedis:
      pool:
        max-active: 50
        max-idle: 20
        min-idle: 5
server:
  port: 81

#logging:
#  config: classpath:logback-spring.xml
#  level: debug
logging:
  level:
    root: info

#udp监听端口
udp:
  ip: 192.168.1.100
  port: 8088